// <auto-generated />
using System;
using HireConnect.ApplicationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HireConnect.ApplicationService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423084802_InitialApplication")]
    partial class InitialApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HireConnect.ApplicationService.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AppliedAt");

                    b.Property<int>("CandidateId")
                        .HasColumnType("integer")
                        .HasColumnName("CandidateId");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("text")
                        .HasColumnName("CoverLetter");

                    b.Property<decimal?>("ExpectedSalary")
                        .HasColumnType("numeric")
                        .HasColumnName("ExpectedSalary");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("JobId");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("Notes");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("text")
                        .HasColumnName("ResumeUrl");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StatusChangedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "CandidateId")
                        .IsUnique();

                    b.ToTable("applications", "application");
                });
#pragma warning restore 612, 618
        }
    }
}
